### ISSUE TITLE
Multiple BTLEserial.write() inside an Arduino Loop

### ISSUE THREAD

**Issue by simar88** [adafruit/Adafruit_nRF8001#20]
Hi everyone,
i'm having a problem using multiple write() inside a loop void with Arduino Mega.
I need to send data over BLE to external devices and the limit of 20 char is a problem for my project.
To avoid this i thought to split my data in multiple messages and sending them inside the same loop but after 5-6 loop the write doesn't work anymore.
Can you help me?
Thanks in advance!

**Comment by DanalEstes** [comment]
See this discussion:

http://forums.adafruit.com/viewtopic.php?f=53&t=70795&p=381409

**Comment by tdicola** [comment]
Looks like the fix for this was merged in with this commit: https://github.com/adafruit/Adafruit_nRF8001/commit/8c3a9a817c9f71e4fcb55fdaa35558d10f27c7a8  Thanks for raising the issue and all the followup in the forums!
