### ISSUE TITLE
when ever i try to upload or verify the file i keep getting this

### ISSUE THREAD

**Issue by disappear123df** [adafruit/Adafruit_nRF8001#22]
home/disappear/sketchbook/libraries/AdafruitnRF8001/utility/hal_aci_tl.cpp: In function ‘void hal_aci_tl_init()’:
/home/disappear/sketchbook/libraries/AdafruitnRF8001/utility/hal_aci_tl.cpp:323:9: error: ‘class SPIClass’ has no member named ‘usingInterrupt’
     SPI.usingInterrupt(HAL_IO_RADIO_IRQ); // add checking for spi conflicts
         ^
/home/disappear/sketchbook/libraries/AdafruitnRF8001/utility/hal_aci_tl.cpp: In function ‘hal_aci_data_t* hal_aci_tl_poll_get()’:
/home/disappear/sketchbook/libraries/AdafruitnRF8001/utility/hal_aci_tl.cpp:366:7: error: ‘class SPIClass’ has no member named ‘beginTransaction’
   SPI.beginTransaction(SPISettings(2000000, LSBFIRST, SPI_MODE0));  // gain control of SPI bus
       ^
/home/disappear/sketchbook/libraries/AdafruitnRF8001/utility/hal_aci_tl.cpp:366:64: error: ‘SPISettings’ was not declared in this scope
   SPI.beginTransaction(SPISettings(2000000, LSBFIRST, SPI_MODE0));  // gain control of SPI bus
                                                                ^
/home/disappear/sketchbook/libraries/AdafruitnRF8001/utility/hal_aci_tl.cpp:407:7: error: ‘class SPIClass’ has no member named ‘endTransaction’
   SPI.endTransaction();              // release the SPI bus
       ^

**Comment by ladyada** [comment]
hhiya you need to use an arduino core with SPI transactions - all modern ones do :)

**Comment by disappear123df** [comment]
ok thanks
