### ISSUE TITLE
Multiple connection not available when module advertising!

### ISSUE THREAD

**Issue by Parsakarami** [adafruit/Adafruit_nRF8001#25]
I use **Adafruit Bluefruit LE SPI** Friend module in my device, when I create my custom services and characteristics and then advertising the services.
During advertising the services I want to connect via some mobile devices (iOS and Android). but when one device find the service and connect to module (when blue led on module turn on), others cannot find module.
Is it possible to connect to module via more than one devices?

**Comment by ladyada** [comment]
nope, btle 4 is point to point
